<?php return array (
  'email_type' => '1',
  'email_safe' => '',
  'mail_address' => '',
  'smtp' => '',
  'smtp_user' => '',
  'smtp_pwd' => '',
  'smtp_port' => '',
  'order_by' => 'new',
  'name' => '喵了个咪',
  'url' => 'http://www.miaolegemi.com',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '<div class=\\"footer\\" style=\\"text-align:center;\\">	<p class=\\"links\\">		<a href=\\"\\">关于我们 </a>|<a href=\\"\\">常见问题</a><a href=\\"\\"> | 联系我们</a> 	</p>	<p class=\\"copyright\\">		Powered by miaolegemi	</p>Copyright © 2018 wtu喵了个咪<br /></div>',
  'tax' => '10',
  'stockup_time' => '1',
  'index_seo_title' => '',
  'index_seo_keywords' => '',
  'index_seo_description' => '',
  'goods_no_pre' => '',
  'commission' => '',
  'store_num_warning' => '1',
  'reg_option' => '0',
  'logo' => 'upload/2018/07/04/20180704075801567.png',
)?>